### ISSUE TITLE
Detect When User Cancels Apple Pay

### ISSUE THREAD

**Issue by db-flutterwave** [yevheniionipko/react-native-apple-payment#6]
I noticed we are not able to detect when users cancel apple pay, I've created a PR [here](https://github.com/yevheniionipko/react-native-apple-payment/pull/5#issue-1582599796) that addresses this, please when you have the time, will appreciate if you take a look. @yevheniionipko 

Anyone else can review and merge if they have sufficient privilege but mentioning you since you are the owner of the repo.

## Usage
With this the user can now perform the following to know if the Apple Pay Payment was cancelled.

```ts
const result = await paymentHandler.initApplePay();
if (result === "CANCELLED_PAYMENT") {
  return handleApplePayCancel()
}
if (result === "COULD_NOT_FIND_TOKEN") {
  return handleApplePayTokenError()
}
return doSomethingWithTheToken(result)
```

**Comment by yevheniionipko** [comment]
Hi, thanks for your time... I will try to find decision or check your pr better

**Comment by yevheniionipko** [comment]
merged, thanks.
use version 1.2.0
