### ISSUE TITLE
canMakePayments working on local development but fails when deployed to testflight.

### ISSUE THREAD

**Issue by np-singh** [yevheniionipko/react-native-apple-payment#8]
Hi all, 

Thank you for the module. I am facing an issue where my module is working all fine on local development but fails when I am deploying to Testflight. `canMakePayments` is returning false. Anyone facing the same?

I am adding Apple Pay Capability using XCode. And I can see that all the apple pay information being added in my entitlement file. 

Any help is appreciated.

Device: IPhone 12 mini running IOS version : 16.3.1

**Comment by yevheniionipko** [comment]
Hi, did you add merchant id? In future I will create flow how add apple pay in xcode project
https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay

if you added merchant id, send me more info about that case
logging details

**Comment by np-singh** [comment]
> Hi, did you add merchant id? In future I will create flow how add apple pay in xcode project https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay
> 
> if you added merchant id, send me more info about that case logging details

Hi, Apologies for not being able to reply early. I was able to solve this by refreshing the keychain certificates. There was some problem with out build process. Thanks.
